baseURL: "https://yliuhz.github.io/blogs" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: LIU Yue's blogs
paginate: 100
theme: 
- hugo-PaperModX
- hugo-cite

# enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsCodeFences: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45
hasCJKLanguage: true


minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        

menu:
  main:
    - name: Archive
      url: archives
      weight: 1
    - name: Search
      url: search/
      weight: 1
    - name: Tags
      url: tags/
      weight: 1
    - name: "@Author"
      url: "https://yliuhz.github.io"
      params:
        external: true
    
               


outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "LIU Yue, Yue LIU, YUE LIU, ZJU, HKUST, yliuhz, liuyuehk, yliumh"
    author: Yue LIU
    # author: ["Me", "You"] # multiple authors

    # defaultTheme: auto
    # # disableThemeToggle: true
    # ShowShareButtons: true
    # ShowReadingTime: true
    # # disableSpecial1stPost: true
    # displayFullLangName: true
    # ShowPostNavLinks: true
    # ShowBreadCrumbs: true
    # ShowCodeCopyButtons: true
    # ShowRssButtonInSectionTermList: true
    # ShowToc: true
    # # comments: false
    # images: ["papermod-cover.png"]


    # theme params
    DisableLanguageSwitch: true
    TocOpen: true
    TocSide: right
    ShowToc: false
    EnableInstantClick: false
    EnableImageZoom: true
    ShowShareButtons: true
    ShareButtons:
        - twitter
        - telegram
    ShowReadingTime: true
    ShowWordCount: true
    ShowCodeCopyButtons: true
    ShowPostNavLinks: true
    Email: yliuhz@outlook.com
    

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "LIU Yue's blogs"
        Content: Welcome to my personal blog. Any discussions are welcome. Reach me by yliuhz@outlook.com. \

            欢迎来到我的个人博客！欢迎讨论！
    socialIcons:
        - name: github-simple
          url: "https://github.com/yliuhz/"
        # - name: rss-simple
        #   url: "https://yliuhz.github.io"
        - name: gmail
          url: email
  
    editPost:
        URL: "https://github.com/yliuhz/blogs/tree/main/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    assets:
        favicon: "https://raw.githubusercontent.com/yliuhz/blogs/master/static/favicon.ico"
        favicon16x16:  "https://raw.githubusercontent.com/yliuhz/blogs/master/static/favicon.ico"
        favicon32x32:  "https://raw.githubusercontent.com/yliuhz/blogs/master/static/favicon.ico"
        apple_touch_icon:  "https://raw.githubusercontent.com/yliuhz/blogs/master/static/favicon.ico"
        safari_pinned_tab:  "https://raw.githubusercontent.com/yliuhz/blogs/master/static/favicon.ico"

# prefer feed.xml rather than index.xml
outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"
    
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        style: github

        
